config/routes.rb
LighthouseForum::Application.routes.draw do

  resources :posts
  root to: 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save 
      redirect_to posts_path 
    else 
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  
  protected
  def post_params
    params.require(:post).permit(:title, :author, :text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LighthouseForum</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%= link_to "Back to this post", post_path(@post) %>
<h2>Edit this post</h2>
<%= form_for @post do |f| %>
  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "author" %><br>
    <%= f.text_field "author" %>
  </div>
  <div>
    <%= f.label "text" %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.submit "Save" %> 
  </div>
<% end %>

app/views/posts/index.html.erb
<h1>Lighthouse Forum</h1>
<hr>
<%= link_to "Create a post!", new_post_path %>
<hr>
<% @posts.each do |post| %>
  <h2><%= link_to post.title, post_path(post) %></h2>
  <p><%= post.text %></p>
  <small>- <%= post.author %></small>
<% end %>

app/views/posts/new.html.erb
<%= link_to "Back to this post", post_path(@post) %>
<h2>Create a post!</h2>
<%= form_for @post do |f| %>
  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "author" %><br>
    <%= f.text_field "author" %>
  </div>
  <div>
    <%= f.label "text" %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.submit "Save" %> 
  </div>
<% end %>

app/views/posts/show.html.erb
<%= link_to "Back to all posts", posts_path %>
<h2><%= @post.title %> (<%= link_to "edit", edit_post_path(@post) %>, <%= link_to "delete", post_path(@post), :method => :delete, :"data-confirm" => "You sure?" %>)</h2>
<p><%= @post.text %></p>
<small>- <%= @post.author %></small>